//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WzComparerR2.MapRender.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WzComparerR2.MapRender.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtCancel4_disabled_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtCancel4_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtCancel4_mouseOver_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtCancel4_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtCancel4_normal_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtCancel4_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtCancel4_pressed_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtCancel4_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtClose3_disabled_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtClose3_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtClose3_mouseOver_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtClose3_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtClose3_normal_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtClose3_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtClose3_pressed_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtClose3_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtNo3_disabled_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtNo3_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtNo3_mouseOver_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtNo3_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtNo3_normal_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtNo3_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtNo3_pressed_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtNo3_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtOK4_disabled_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtOK4_disabled_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtOK4_mouseOver_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtOK4_mouseOver_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtOK4_normal_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtOK4_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_BtOK4_pressed_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_BtOK4_pressed_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ComboBox_normal_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ComboBox_normal_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ComboBox_normal_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ComboBox_normal_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ComboBox_normal_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ComboBox_normal_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_Notice6_box
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_Notice6_box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_Notice6_c
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_Notice6_c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_Notice6_c_box
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_Notice6_c_box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_Notice6_s
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_Notice6_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_Notice6_s_box
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_Notice6_s_box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_Notice6_t
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_Notice6_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_0
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_1
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_2
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_3
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_4
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_5
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_6
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_7
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_8
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_9
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_0_left
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_0_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Basic_img_ShowLevel_Bracket_right
        {
            get
            {
                object obj = ResourceManager.GetObject("Basic_img_ShowLevel_Bracket_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusBar3_img_chat_ingame_input_layer_backgrnd
        {
            get
            {
                object obj = ResourceManager.GetObject("StatusBar3_img_chat_ingame_input_layer_backgrnd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusBar3_img_chat_ingame_input_layer_chatEnter
        {
            get
            {
                object obj = ResourceManager.GetObject("StatusBar3_img_chat_ingame_input_layer_chatEnter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusBar3_img_chat_ingame_view_max_bottom
        {
            get
            {
                object obj = ResourceManager.GetObject("StatusBar3_img_chat_ingame_view_max_bottom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusBar3_img_chat_ingame_view_max_center
        {
            get
            {
                object obj = ResourceManager.GetObject("StatusBar3_img_chat_ingame_view_max_center", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusBar3_img_chat_ingame_view_max_top
        {
            get
            {
                object obj = ResourceManager.GetObject("StatusBar3_img_chat_ingame_view_max_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_ArcaneForce
        {
            get
            {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_ArcaneForce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_AuthenticForce
        {
            get
            {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_AuthenticForce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_enchantMob
        {
            get
            {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_enchantMob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_Line
        {
            get
            {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_Line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_Mob
        {
            get
            {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_Mob", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_Npc
        {
            get
            {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_Npc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow_img_ToolTip_WorldMap_StarForce
        {
            get
            {
                object obj = ResourceManager.GetObject("UIWindow_img_ToolTip_WorldMap_StarForce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow2_img_Teleport_customBG
        {
            get
            {
                object obj = ResourceManager.GetObject("UIWindow2_img_Teleport_customBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow2_img_WorldMap_Border_0
        {
            get
            {
                object obj = ResourceManager.GetObject("UIWindow2_img_WorldMap_Border_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow3_img_mirrorFrame_1024
        {
            get
            {
                object obj = ResourceManager.GetObject("UIWindow3_img_mirrorFrame_1024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow3_img_mirrorFrame_1366
        {
            get
            {
                object obj = ResourceManager.GetObject("UIWindow3_img_mirrorFrame_1366", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UIWindow3_img_mirrorFrame_800
        {
            get
            {
                object obj = ResourceManager.GetObject("UIWindow3_img_mirrorFrame_800", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}